<a href="https://colab.research.google.com/github/Leemyunglyul/ai_advanced/blob/main/%5BSDS%5DWS_Numpy_Q_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 연습 문제

In [ ]:
import numpy as np

#### 배열 생성

 - [1, 4, 5, 6, 7] 값을 갖는 1D 배열을 생성한 후 arr 변수에 저장하고 변수보기로 출력하시오
 - arr를 print로 출력하시오

In [ ]:
arr = np.array([1,4,5,6,7])

In [ ]:
print(arr)

[1 4 5 6 7]


- [[1,4,5], [5,6,7]] 값을 갖는 2D 배열을 생성한 후 arr2 변수에 저장하고 변수보기로 출력하시오
- arr2를 print로 출력하시오

In [ ]:
arr2 = np.array([[1,4,5], [5,6,7]])

In [ ]:
print(arr2)

[[1 4 5]
 [5 6 7]]


 - 1~10 값을 갖는 1D 배열 생성 후 출력

In [ ]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


- 3.14~3.28 값을 0.01 단위로 갖는 1D 배열 생성 후 출력

In [ ]:
arr = np.arange(3.14, 3.28, 0.01)
print(arr)

[3.14 3.15 3.16 3.17 3.18 3.19 3.2  3.21 3.22 3.23 3.24 3.25 3.26 3.27]


 - 100~-100까지 감소하는 1D 배열을 생성 후 출력

In [ ]:
arr = np.arange(100, -101, -1)
print(arr)

[ 100   99   98   97   96   95   94   93   92   91   90   89   88   87
   86   85   84   83   82   81   80   79   78   77   76   75   74   73
   72   71   70   69   68   67   66   65   64   63   62   61   60   59
   58   57   56   55   54   53   52   51   50   49   48   47   46   45
   44   43   42   41   40   39   38   37   36   35   34   33   32   31
   30   29   28   27   26   25   24   23   22   21   20   19   18   17
   16   15   14   13   12   11   10    9    8    7    6    5    4    3
    2    1    0   -1   -2   -3   -4   -5   -6   -7   -8   -9  -10  -11
  -12  -13  -14  -15  -16  -17  -18  -19  -20  -21  -22  -23  -24  -25
  -26  -27  -28  -29  -30  -31  -32  -33  -34  -35  -36  -37  -38  -39
  -40  -41  -42  -43  -44  -45  -46  -47  -48  -49  -50  -51  -52  -53
  -54  -55  -56  -57  -58  -59  -60  -61  -62  -63  -64  -65  -66  -67
  -68  -69  -70  -71  -72  -73  -74  -75  -76  -77  -78  -79  -80  -81
  -82  -83  -84  -85  -86  -87  -88  -89  -90  -91  -92  -93  -94  -95
  -96 

### 배열 속성

In [ ]:
arr = np.array([[1,4,5], [5,6,7]])
arr

array([[1, 4, 5],
       [5, 6, 7]])

 - ndim 조회

In [ ]:
arr.ndim

2

 - shape 조회

In [ ]:
arr.shape

(2, 3)

 - 요소 수 조회

In [ ]:
arr.size

6

 - 데이터 타입 조회

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
type(arr)

numpy.ndarray

 - 배열 전치

In [ ]:
arr.T

array([[1, 5],
       [4, 6],
       [5, 7]])

### 배열 형태 변경

In [ ]:
arr = np.array([[1,4,5], [5,6,7]])
arr

array([[1, 4, 5],
       [5, 6, 7]])

 - arr를 1D 배열로 변경 후 arr1d에 저장 후 배열 및 shape 출력

In [ ]:
arr1d = arr.flatten()
print(arr1d)
print(arr1d.shape)

[1 4 5 5 6 7]
(6,)


In [ ]:
arr1d = arr.reshape(-1)
print(arr1d)
print(arr1d.shape)


[1 4 5 5 6 7]
(6,)


In [ ]:
arr1d = arr.ravel()
print(arr1d)
print(arr1d.shape)


[1 4 5 5 6 7]
(6,)


- arr1d를 3행 2열의 2D 배열로 변경 후 arr2d에 저장 후 배열 및 shape 출력

In [ ]:
arr2d = arr1d.reshape(3,2)
print(arr2d)
print(arr2d.shape)


[[1 4]
 [5 5]
 [6 7]]
(3, 2)


 - arr1d를 열이 1개인 2D 배열로 변경 후 arr2d에 저장 후 배열 및 shape 출력

In [ ]:
arr2d = arr1d.reshape(-1, 1 )
print(arr2d)
print(arr2d.shape)

[[1]
 [4]
 [5]
 [5]
 [6]
 [7]]
(6, 1)


### 데이터 타입 변경

- array 함수를 이용하여 리스트를 [1,2,3,4] 실수형으로 생성하시오

In [ ]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

- arange 함수를 이용하여 1~10 정수를 갖는 arr를 생성 후 실수 타입으로 변경하시오

In [ ]:
np.arange(1, 11, dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.arange(1, 11).astype(float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 배열 연산

In [ ]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([3,4,5,7,8,9])
arr1, arr2

(array([1, 2, 3, 4, 5, 6]), array([3, 4, 5, 7, 8, 9]))

 - arr1과 arr2를 더한 후 -10을 하여 arr3에 저장하시오

In [ ]:
arr3 = arr1 + arr2 - 10
arr3

array([-6, -4, -2,  1,  3,  5])

 - arr3의 값이 양수인지 확인하시오


In [ ]:
arr3 = arr3 > 0
arr3

array([False, False, False,  True,  True,  True])

 - arr3의 값이 0보다 작은 짝수인지 비교하시오.

In [ ]:
arr3 = (arr3<0) & (arr3%2==0)
arr3

array([False, False, False, False, False, False])

### 배열 조회

In [ ]:
arr = np.arange(1, 26).reshape(5,-1)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

mm.jaen.kr
sds2603
sds0825

 - 아래의 결과가 출력되도록 배열을 조회하거나 값을 수정하세요.

In [ ]:
arr[2, 3]

np.int64(14)

In [ ]:
arr[arr == 14]

array([14])

In [ ]:
arr[:, 1]

array([ 2,  7, 12, 17, 22])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[4]

array([21, 22, 23, 24, 25])

In [ ]:
arr[0:3, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [ ]:
# slicing + fancy
arr[:, [1, 2, 4]]

array([[ 2,  3,  5],
       [ 7,  8, 10],
       [12, 13, 15],
       [17, 18, 20],
       [22, 23, 25]])

In [ ]:
# fancy
arr[[2, 2, 3], [2, 3, 4]]

array([13, 14, 20])

In [ ]:
# boolean
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [ ]:
# boolean
arr[(arr >= 12) & (arr % 3 == 0)]

array([12, 15, 18, 21, 24])

In [ ]:
# 홀수 부호 변경
np.where(arr % 2 == 1, -arr, arr)

array([[ -1,   2,  -3,   4,  -5],
       [  6,  -7,   8,  -9,  10],
       [-11,  12, -13,  14, -15],
       [ 16, -17,  18, -19,  20],
       [-21,  22, -23,  24, -25]])

### 기술 통계 및 기타 함수

In [ ]:
np.random.seed(1024)
idx = np.random.choice(25, 5, replace=False)
arr = np.random.randint(1, 100, 25)
arr[idx] = 0
arr = arr.reshape(5, -1)
arr

array([[70, 28, 20, 49,  0],
       [31,  0, 55, 48, 77],
       [ 6, 60, 71, 21,  0],
       [98, 16, 66, 41, 27],
       [91,  0,  0, 95, 13]])

- arr의 전체 합을 출력하시오

In [ ]:
arr.sum()

np.int64(983)

- arr의 열 별 합을 출력하시오

In [ ]:
arr.sum(axis=0)

array([296, 104, 212, 254, 117])

 - arr의 열 별 평균을 출력하시오

In [ ]:
arr.mean(axis=0)

array([59.2, 20.8, 42.4, 50.8, 23.4])

 - arr의 열 별 모분산을 출력하시오

In [ ]:
arr.var(axis=0)

array([1251.76,  495.36,  766.64,  589.76,  817.84])

 - arr의 열 별 표본분산을 출력하시오

In [ ]:
arr.std(axis=0)

array([35.38022046, 22.25668439, 27.68826466, 24.28497478, 28.59790202])

 - arr의 열 별 표분표준편차를 소수점 3자리까지 출력하시오

In [ ]:
arr.std(axis=0).round(3)

array([35.38 , 22.257, 27.688, 24.285, 28.598])

 - arr의 열 별 표분표준편차를 출력하되, 분산 함수와 제곱근 함수를 이용하시오
   - np.sqrt(arr)

In [ ]:
np.sqrt(arr.var(axis=0))

array([35.38022046, 22.25668439, 27.68826466, 24.28497478, 28.59790202])

- arr의 열 별 합의 합을 출력하시오

In [ ]:
arr.sum(axis=0).sum()

np.int64(983)

- arr의 행 별 중앙값을 출력하시오

In [ ]:
np.median(arr, axis=1)

array([28., 48., 21., 41., 13.])

- arr의 행 별로 가장 큰 값을 출력하시오

In [ ]:
arr.max(axis=1)

array([70, 77, 71, 98, 95])

 - arr의 행 별 가장 큰 값의 위치(index)를 idx 변수에 저장하고 출력하시오

In [ ]:
idx = arr.argmax(axis=1)
idx

array([0, 4, 2, 0, 3])

- arr의 전체에 한 개라도 참인 값이 있는 지 확인하시오

In [ ]:
arr.any()

np.True_

- arr의 열 중 모든 값이 참인 열이 있는 지 확인하시오

In [ ]:
arr.all(axis=0)

array([ True, False, False,  True, False])

 - arr의 열 중 거짓 값이 하나라도 포함된 열이 있는 지 확인하시오

In [ ]:
~ arr.all(axis = 0)

array([False,  True,  True, False,  True])

 - arr의 행 중 참이 한 개도 없는 열이 있는 지 확인하시오

In [ ]:
~ arr.any(axis = 1)

array([False, False, False, False, False])