<a href="https://colab.research.google.com/github/Leemyunglyul/ai_advanced/blob/main/%5BSDS%5DChap_2_Numpy_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## 배열 생성

In [ ]:
import numpy as np
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array([[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0.1, 1.1, 0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [ ]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.full((2,2), -1)

array([[-1, -1],
       [-1, -1]])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

## 배열 속성

In [ ]:
array = np.array([[1, 2], [3, 4]])
print('array의 차원:', array.ndim)

array의 차원: 2


In [ ]:
print('array의 각 차원별 크기:', array.shape)

array의 각 차원별 크기: (2, 2)


In [ ]:
print('array의 요소의 총 개수 :', array.size)

array의 요소의 총 개수 : 4


In [ ]:
print('array의 데이터 유형 :', array.dtype)

array의 데이터 유형 : int64


In [ ]:
print('array의 전치 (전) :')
print(array)
print('array의 전치 (후) :')
print(array.T)

array의 전치 (전) :
[[1 2]
 [3 4]]
array의 전치 (후) :
[[1 3]
 [2 4]]


## 배열 형태 변경

In [ ]:
array = np.arange(16)
array, array.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 (16,))

In [ ]:
array.reshape(4, 4), array.reshape(4, 4).shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 (4, 4))

In [ ]:
array.reshape(-1, 8), array.reshape(-1, 8).shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 (2, 8))

## 배열 데이터 타입 변경

In [ ]:
x = np.array([[1,2], [3,4]])
x, x.dtype

(array([[1, 2],
        [3, 4]]),
 dtype('int64'))

In [ ]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
x, x.dtype

(array([[1., 2.],
        [3., 4.]]),
 dtype('float64'))

In [ ]:
x.astype(np.int32)

array([[1, 2],
       [3, 4]], dtype=int32)

In [ ]:
np.int32(x)

array([[1, 2],
       [3, 4]], dtype=int32)

In [ ]:
x.astype('int')

array([[1, 2],
       [3, 4]])

## 배열 인덱싱

### 정수 인덱싱

In [ ]:
array = np.arange(9).reshape(3, 3)
array[0]

array([0, 1, 2])

In [ ]:
array[-1]

array([6, 7, 8])

In [ ]:
array[0, 0]

np.int64(0)

In [ ]:
array[-1, -1]

np.int64(8)

### 불리언 인덱싱

In [ ]:
bidx = array % 2 == 0
bidx

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [ ]:
array[bidx]

array([0, 2, 4, 6, 8])

In [ ]:
array[array > 5]

array([6, 7, 8])

### 팬시 인덱싱

In [ ]:
row = [0, 1]
col = [2, 1]
array[row, col]

array([2, 4])

In [ ]:
array[[0,1], [2, 1]]

array([2, 4])

In [ ]:
array[0, 2], array[1, 1]

(np.int64(2), np.int64(4))

### 슬라이싱

In [ ]:
array[0, :]

array([0, 1, 2])

In [ ]:
array[:, 1]

array([1, 4, 7])

In [ ]:
array[:2, 1:]

array([[1, 2],
       [4, 5]])

In [ ]:
array[-1:, 1:3]

array([[7, 8]])

## 기술 통계 함수

In [ ]:
array.sum()

np.int64(36)

In [ ]:
array.sum(axis=0)

array([ 9, 12, 15])

In [ ]:
array.sum(axis=1)

array([ 3, 12, 21])