<a href="https://colab.research.google.com/github/Leemyunglyul/ai_advanced/blob/main/%5BSDS%5DChap_2_Numpy_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## 배열 생성

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
display(arr)
print(arr) # 출력 양식이 다름

array([1, 2, 3, 4])

[1 2 3 4]


In [ ]:
arr = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.array([[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]]])
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
# arange(start, stop, step) -> 실수도 가능함
# stop 미포함
# 1D 배열
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0.1, 1.1, 0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
# 구간(bins) 배열 생성 -> 일정한 간격(자동 계산)의 값을 갖는 배열
# linspace(start, stop, 개수)
# stop 포함
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
np.ones((2, 2)), np.ones_like(arr)

(array([[1., 1.],
        [1., 1.]]),
 array([1, 1, 1, 1, 1]))

In [ ]:
np.zeros((2, 2)), np.zeros_like(arr)

(array([[0., 0.],
        [0., 0.]]),
 array([0, 0, 0, 0, 0]))

In [ ]:
np.full((2,2), -1), np.full_like(arr, -1)

(array([[-1, -1],
        [-1, -1]]),
 array([-1, -1, -1, -1, -1]))

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

## 배열 속성

In [ ]:
array = np.array([[1, 2], [3, 4]])
print('array의 차원:', array.ndim)

array의 차원: 2


In [ ]:
print('array의 각 차원별 크기:', array.shape)

array의 각 차원별 크기: (2, 2)


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.shape

(5,)

In [ ]:
len(array) # 0번 축의 크기

2

In [ ]:
np.random.randn(2, 2, 3).size

12

In [ ]:
# shape의 모든 축을 다 곱한 값
print('array의 요소의 총 개수 :', array.size)

array의 요소의 총 개수 : 4


In [ ]:
print('array의 데이터 유형 :', array.dtype)

array의 데이터 유형 : int64


In [ ]:
print('array의 전치 (전) :')
print(array)
print('array의 전치 (후) :')
print(array.T)

array의 전치 (전) :
[[1 2]
 [3 4]]
array의 전치 (후) :
[[1 3]
 [2 4]]


## 배열 형태 변경

In [ ]:
# shape 변경
array = np.arange(16) # 0~15의 정수 1D 배열
array, array.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 (16,))

In [ ]:
# array.reshape(축 별 크기, ...)
# np.reshape(arr, shape)
# 지정한 축 별 크기 또는 shape의 size가 array의 size와 동일
# array.shape 메소드
arr1 = array.reshape(4, 4)
arr1, arr1.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 (4, 4))

In [ ]:
# np.reshape 함수
np.reshape(array, (4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# 1개 축만 -1 설정 가능 (자동 계산)
array.reshape(-1, 8), array.reshape(2, -1).shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 (2, 8))

In [ ]:
arr1 = array.reshape(4, 4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr1.reshape(-1) # 1d 변경 -> view

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr1.ravel() # 1d 변경 -> view

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr1.flatten() # 1d 변경 -> copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr1 = array # arr1과 array 동일 (reference)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# data는 공유, 속성은 따로
# reshape, ravel이 view 생성
arr1 = array.view()

In [ ]:
arr2 = array.reshape(4, 4)
arr2[0, 0] = 1000 # view라서 데이터를 공유
arr2, array

(array([[1000,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11],
        [  12,   13,   14,   15]]),
 array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11,   12,   13,   14,   15]))

In [ ]:
# flatten은 copy
arr1 = array.copy() # 속성, 데이터 모두 따로

## 배열 데이터 타입 변경

In [ ]:
x = np.array([[1,2], [3,4]])
x, x.dtype

(array([[1, 2],
        [3, 4]]),
 dtype('int64'))

In [ ]:
np.sctypeDict

{'bool': numpy.bool,
 'float16': numpy.float16,
 'float32': numpy.float32,
 'float64': numpy.float64,
 'longdouble': numpy.longdouble,
 'complex64': numpy.complex64,
 'complex128': numpy.complex128,
 'clongdouble': numpy.clongdouble,
 'bytes_': numpy.bytes_,
 'str_': numpy.str_,
 'void': numpy.void,
 'object_': numpy.object_,
 'datetime64': numpy.datetime64,
 'timedelta64': numpy.timedelta64,
 'int8': numpy.int8,
 'byte': numpy.int8,
 'uint8': numpy.uint8,
 'ubyte': numpy.uint8,
 'int16': numpy.int16,
 'short': numpy.int16,
 'uint16': numpy.uint16,
 'ushort': numpy.uint16,
 'int32': numpy.int32,
 'intc': numpy.int32,
 'uint32': numpy.uint32,
 'uintc': numpy.uint32,
 'int64': numpy.int64,
 'long': numpy.int64,
 'uint64': numpy.uint64,
 'ulong': numpy.uint64,
 'longlong': numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'intp': numpy.int64,
 'uintp': numpy.uint64,
 'double': numpy.float64,
 'cdouble': numpy.complex128,
 'single': numpy.float32,
 'csingle': numpy.complex64,
 'half': numpy.

In [ ]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
x, x.dtype

(array([[1., 2.],
        [3., 4.]]),
 dtype('float64'))

In [ ]:
x = x.astype(np.int32) # 원본 수정X, 수정된 배열 반환
x

array([[1, 2],
       [3, 4]], dtype=int32)

In [ ]:
np.int32(x)

array([[1, 2],
       [3, 4]], dtype=int32)

In [ ]:
x.astype('int')

array([[1, 2],
       [3, 4]])

## 배열 인덱싱

### 정수 인덱싱

In [ ]:
array = np.arange(9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 배열의 차원 크기와 무관하게 1D처럼 액세스
# 0번 축만 이용하여 선택
array[0] # 2D -> 1D

array([0, 1, 2])

In [ ]:
array[-1]

array([6, 7, 8])

In [ ]:
array[2][1] # 파이썬의 구독

np.int64(7)

In [ ]:
# array[0번축idx, 1번idx, ....]
array[2, 1] # 넘파이 배열의 액세스 형태

np.int64(7)

In [ ]:
array[0, 0]

np.int64(0)

In [ ]:
array[-1, -1]

np.int64(8)

In [ ]:
array.tolist()

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

### 불리언 인덱싱

In [ ]:
# 배열 연산 (element-wise)
# 동일 인덱스 (위치)끼리 연산
arr1 = np.arange(1, 5).reshape(2,2)
arr2 = np.arange(10, 50, 10).reshape(2,2)
arr1 - arr2 # 사칙, 비교 연산 모두 가능

array([[False, False],
       [False, False]])

In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([10, 20])
arr1.shape, arr2.shape
arr1+arr2

array([[11, 22],
       [13, 24]])

In [ ]:
# Broadcast: shape이 다른 배열끼리 연산
# (3, 1, 2), (1, 4, 2)
# 같은 축(번호)의 크기가 동일 또는 한쪽 1
arr1 = np.ones((3, 1, 2))
arr2 = np.ones((1, 4, 2))
arr1 + arr2, (arr1+arr2).shape

(array([[[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]],
 
        [[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]],
 
        [[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]]]),
 (3, 4, 2))

In [ ]:
arr1 % 2 == 0 # 배열과 스칼라 간의 연산 가능

array([[False,  True],
       [False,  True]])

In [ ]:
a = 10

a % 2 == 0 and a > 5 # 파이썬 논리 연산

True

In [ ]:
cond1 = arr1 % 2 == 0
cond2 = arr1 > 5
cond1 and cond2 # 파이썬 논리 연산자 사용 불가

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# 비트 연산자를 논리 대신 사용
cond1 = arr1 % 2 == 0
cond2 = arr1 > 5
cond1 & cond2

array([[False, False],
       [False, False]])

In [ ]:
(arr1 % 2 == 0) & (arr1 > 5)

array([[False, False],
       [False, False]])

In [ ]:
arr1[1] = 1000
arr1

array([[   1,    2],
       [1000, 1000]])

In [ ]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 인덱스 자리에 bool 타입의 리스트/터플/배열
bidx = array % 2 == 0
bidx

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [ ]:
array[bidx] # 결과는 1D

array([0, 2, 4, 6, 8])

In [ ]:
# 넘파이 불리언 인덱싱은 주로 1D에 사용
array[array > 5] = 1000
array

array([[   0,    1,    2],
       [   3,    4,    5],
       [1000, 1000, 1000]])

### 팬시 인덱싱
 - 인덱스 자리에 인덱스의 목록(list, tuple, array)

In [ ]:
arr = np.arange(11, 21)
idx = [5, 2, 3, 5]
arr[idx] # 순서, 중복 무시하고 원하는 값을 추출

array([16, 13, 14, 16])

In [ ]:
row = [0, 1]
col = [2, 1]
array[row, col]

array([2, 4])

In [ ]:
array[[0,1], [2, 1]]

array([2, 4])

In [ ]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
array[[0,1], [1]], array[[0,1], 1]

(array([1, 4]), array([1, 4]))

In [ ]:
# 인덱스 개수 상이, 둘 다 1개 초과
# 오류
array[[0,1], [1, 2, 2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [ ]:
array[0, 2], array[1, 1]

(np.int64(2), np.int64(4))

### 슬라이싱

In [ ]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 0번 축에 대해 두 번 1:3 슬라이싱
array[1:3][1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 0번 축, 1번 축에 대해 각각 1:3 슬라이싱
array[1:3, 1:3]

array([4, 7])

In [ ]:
array[1:3, 1:2] # ss 2D

array([[4],
       [7]])

In [ ]:
array[1:3, 1] # si 1D

array([4, 7])

In [ ]:
array[0, :]

array([0, 1, 2])

In [ ]:
array[:, 1]

array([1, 4, 7])

In [ ]:
array[:2, 1:]

array([[1, 2],
       [4, 5]])

In [ ]:
a = array[-1:, 1:3] # 슬라이싱 후 저장 -> view
a

array([[7, 8]])

## 기술 통계 함수

In [ ]:
arr = np.arange(10).reshape(2, -1)
arr.sum(axis=1)

array([10, 35])

In [ ]:
array.sum()

np.int64(36)

In [ ]:
array.sum(axis=0)

array([ 9, 12, 15])

In [ ]:
array.sum(axis=1)

array([ 3, 12, 21])